import type { GenerationTask } from "./types";

const now = Date.now();

export const seedGenerationTasks: GenerationTask[] = [
  {
    id: "task-neon-city",
    type: "image",
    status: "running",
    prompt: "Неоновый киберпанк-город под дождём, вид сверху",
    model: "Midjourney v6",
    progress: 64,
    createdAt: now - 1000 * 60 * 12,
    updatedAt: now - 1000 * 20,
    etaSeconds: 30,
    durationSeconds: 30,
    credits: 80,
    error: null,
  },
  {
    id: "task-mountain-drone",
    type: "video",
    status: "running",
    prompt: "Дрон-облёт горного озера на рассвете, 5 сек",
    model: "Kling 3.0",
    progress: 28,
    createdAt: now - 1000 * 60 * 11,
    updatedAt: now - 1000 * 15,
    etaSeconds: 120,
    durationSeconds: 120,
    credits: 150,
    error: null,
  },
  {
    id: "task-coffee-script",
    type: "text",
    status: "queued",
    prompt: "Сценарий рекламного ролика для кофейни, 30 секунд",
    model: "GPT-4o",
    progress: 0,
    createdAt: now - 1000 * 60 * 8,
    updatedAt: now - 1000 * 60 * 8,
    etaSeconds: 40,
    durationSeconds: 40,
    credits: 6,
    error: null,
  },
  {
    id: "task-cafe-logo",
    type: "image",
    status: "done",
    prompt: "Минималистичный логотип кофейни, бежевые тона",
    model: "Flux",
    progress: 100,
    createdAt: now - 1000 * 60 * 24,
    updatedAt: now - 1000 * 60 * 18,
    etaSeconds: 0,
    durationSeconds: 12,
    credits: 80,
    error: null,
  },
  {
    id: "task-greeting-voice",
    type: "audio",
    status: "failed",
    prompt: "Озвучка приветствия мужским голосом",
    model: "ElevenLabs",
    progress: 34,
    createdAt: now - 1000 * 60 * 32,
    updatedAt: now - 1000 * 60 * 26,
    etaSeconds: 0,
    durationSeconds: 50,
    credits: 18,
    error: "Недостаточно кредитов",
  },
  {
    id: "task-retro-poster",
    type: "image",
    status: "canceled",
    prompt: "Постер в стиле ретро-футуризм 80-х",
    model: "Seedream",
    progress: 18,
    createdAt: now - 1000 * 60 * 45,
    updatedAt: now - 1000 * 60 * 40,
    etaSeconds: 0,
    durationSeconds: 80,
    credits: 50,
    error: null,
  },
  {
    id: "task-brand-copy",
    type: "text",
    status: "queued",
    prompt: "Три коротких слогана для страницы подписки",
    model: "GPT-5.1",
    progress: 0,
    createdAt: now - 1000 * 60 * 5,
    updatedAt: now - 1000 * 60 * 5,
    etaSeconds: 45,
    durationSeconds: 45,
    credits: 4,
    error: null,
  },
  {
    id: "task-product-shot",
    type: "image",
    status: "done",
    prompt: "Предметный кадр стакана кофе на тёмном фоне",
    model: "Nano Banana Pro",
    progress: 100,
    createdAt: now - 1000 * 60 * 58,
    updatedAt: now - 1000 * 60 * 52,
    etaSeconds: 0,
    durationSeconds: 18,
    credits: 60,
    error: null,
  },
  {
    id: "task-social-cut",
    type: "video",
    status: "queued",
    prompt: "Вертикальный ролик для соцсетей на 7 секунд",
    model: "Runway Gen-4",
    progress: 0,
    createdAt: now - 1000 * 60 * 4,
    updatedAt: now - 1000 * 60 * 4,
    etaSeconds: 180,
    durationSeconds: 180,
    credits: 120,
    error: null,
  },
  {
    id: "task-menu-photo",
    type: "image",
    status: "queued",
    prompt: "Фото новой позиции меню для карточки товара",
    model: "Flux",
    progress: 0,
    createdAt: now - 1000 * 60 * 3,
    updatedAt: now - 1000 * 60 * 3,
    etaSeconds: 70,
    durationSeconds: 70,
    credits: 35,
    error: null,
  },
  {
    id: "task-jingle",
    type: "audio",
    status: "queued",
    prompt: "Короткий джингл для заставки кофейни",
    model: "Suno Studio",
    progress: 0,
    createdAt: now - 1000 * 60 * 2,
    updatedAt: now - 1000 * 60 * 2,
    etaSeconds: 110,
    durationSeconds: 110,
    credits: 28,
    error: null,
  },
];
